### ISSUE TITLE
Grep Error "grep: warning: stray \ before /"

### ISSUE THREAD

**Issue by stephenjharrington** [cynicastic/scribe#24]
@cynicastic

After a recent Entware update to AsusWRT-Merlin/AMTM, grep was updated (2.5.3?) and now when running the scribe "s" option for "Show scribe status" you get a " "grep: warning: stray \ before /" message displayed when it gets to the "syslog-ng.conf version check" stage.

Grep reference is here:-
[https://git.savannah.gnu.org/cgit/grep.git/commit/?id=e7f8e8eb1fd41b308ee10741bbd8068acc1847c2](url)

This can be fixed by removing the "\\" before the "/" on line 365:-

        man_vers="$( grep -oE 'on\/[0-9]{1,2}([_.][0-9]{1,2})' $sng_conf )"

Any chance of fixing it "officially" and pushing out an update please?

**Comment by cynicastic** [comment]
Okay, the good news is, it's just a warning.  I'd like to investigate a bit more, what is there now I thought was the documented usage, so I'd like to understand it not just patch it.

I'll be able to work on it after the first of the year, the next week or so will be crazy for me.

**Comment by stephenjharrington** [comment]
Crazy time of the year for all of us! :-)
Have a good holiday season and when you get to it, you get to it - as you say nothing even remotely fatal or urgent.

**Comment by cynicastic** [comment]
Fixed in just pushed 2.4.4.
