### ISSUE TITLE
"rs. Restart syslog-ng" fails with "error connecting control socket..." error

### ISSUE THREAD

**Issue by ScottWell1** [cynicastic/scribe#25]
Like the grep error in issue #24, I think this began with the last entware update. 

When “rs. Restart” is selected in scribe, an error is produced when calling syslog-ng-ctl, "error connecting control socket, socket='/opt/var/run/syslog-ng/syslog-ng.ctl".

The default location for the .ctl and .pid file in previous versions of syslog-ng and syslog-ng-ctl was /opt/var/run.  Now it is /opt/var/run/syslog-ng.  If the folder does not exist, the error is thrown.

Simply creating the /opt/var/run/syslog-ng folder solves it, so perhaps that folder creation can be added to the install and upgrade scripts.

**Comment by cynicastic** [comment]
Oh, I see.  Using syslog-ng.ctl, not a regular use of scribe.  Duh.  Lemme look into it.

**Comment by ScottWell1** [comment]
Apologies, I stated "rs. Restart" but the problem is with "rl. Reload".  

The "rl. Reload" calls syslog-ng-ctl, and it's latest version throws error if the  /opt/var/run/syslog-ng" folder does not exist.

**Comment by cynicastic** [comment]
Also with "lc".   So, although I can specify the location of the ctl and pid files, guess what, syslog-ng-ctl ignores that.

Your solution is the correct one, I'm adding creation / checking of that directory now.

I wish syslog-ng would just stop arbitrarily changing things.  Sometimes I think they do it just to get more people paying for support.  If I knew then what I know now about syslog-ng, I probably wouldn't have done this, keeping up with their changes is getting old.  Upstream is now 4.0.0, I shudder to think what madness lies there.  </rant>

**Comment by ScottWell1** [comment]
Agreed, changes like that which "break" existing use cases are just reckless.  I like the idea of the subfolder, but it seems like they could have just automatically created the folder instead of failing. 

Thanks for the continued support!  The scribe script makes syslog-ng setup and maintenance a lot easier!

**Comment by cynicastic** [comment]
Okay, should be fixed, Pushed a minor change, now 2.4.4.

**Comment by ScottWell1** [comment]
Looks good!  I deleted my existing /opt/var/run/syslog-ng folder and updated to 2.4.4.  An initial "rl-Reload" threw an error, but a "rs-Restart" created the folder -- and subsequent "rl-Reload" usage works without error.

THANK YOU, this should save some other users from seeing errors!
